 questions = [{
             "src": "joy-1-1-bounce.gif",
             "id": "joy-1-1-bounce",
             "story_id": "joy-1-1",
             "animation": "bounce",
             "vis": "bar",
             "affect": "joy",
             "topic": "vacation",
             "category": "kineticharts",
             "story": "What's your choice for vacation? A survey shows that most families would like to go to a beach, visit a theme park or national park, go on a road trip, or have fun at an all-inclusive resort.",
         },
         {
             "src": "joy_2.gif",
             "id": "2",
             "story": "When people go on a vacation? A survey shows that most people enjoy spending vacation in summer.",
         },
         {
             "src": "surprise_1.gif",
             "id": "3",
             "story": "Why people travel on vacation? A survey shows that there are 5 main reasons.",
         },
         {
             "src": "surprise_2.gif",
             "id": "4",
             "story": "Watching movies is one of the most popular entertainment around the world. Let's see the top 5 movies that have earned the highest box office!",
         },
         {
             "src": "excitement_1.gif",
             "id": "5",
             "story": "Comedy is always one of the most popular moview genres. It used to be really prominent in the 20th century, and now it has been steadily occupying about one quater of the movie market.",
         },
         {
             "src": "excitement_2.gif",
             "id": "6",
             "story": "What food do people like to eat when watching movies? A survey shows that popcorn, nachos, chocolate, candies, and cookies/biscuit are the top 5 choices.",
         },
         {
             "src": "tenderness_1.gif",
             "id": "7",
             "story": "The world may be more unequal than you thought. In Middle East, 10% people earn 61% of the national income.",
         },
         {
             "src": "tenderness_2.gif",
             "id": "8",
             "story": "In the US, top 1% people earn about 20% of the national income, and this proportion is even becoming higher.",
         },
         {
             "src": "amusement_1.gif",
             "id": "9",
             "story": "In America, 40% people share only 0.3% of all the money while top 20% people occupy 84%.",
         },
         {
             "src": "amusement_2.gif",
             "id": "10",
             "story": "Do you know how long animals sleep everyday? Brown bats sleep 20 hours per day, cats sleep 12 hours per day, while giraffe only need 2-hour sleep!",
         },
         {
             "src": "amusement_1.gif",
             "id": "11",
             "story": "The population of cheetahs is decreasing at a shocking speed. In 1900, there are 100 thousand cheetah worldwide, but some scientists prediected that the population will quickly shrink to nearly 0.",
         },
     ]
     //[
     //         { "src": "439.png", "id": "439" },
     //         { "src": "438.png", "id": "438" },
     //         { "src": "459.png", "id": "459" },
     //         { "src": "471.png", "id": "471" },
     //         { "src": "465.png", "id": "465" },
     //         { "src": "511.jpg", "id": "511" },
     //         { "src": "505.png", "id": "505" },
     //         { "src": "504.png", "id": "504" },
     //         { "src": "510.jpg", "id": "510" },
     //         { "src": "464.png", "id": "464" },
     //         { "src": "470.png", "id": "470" },
     //         { "src": "458.png", "id": "458" },
     //         { "src": "466.png", "id": "466" },
     //         { "src": "472.png", "id": "472" },
     //         { "src": "499.png", "id": "499" },
     //         { "src": "512.png", "id": "512" },
     //         { "src": "506.png", "id": "506" },
     //         { "src": "513.png", "id": "513" },
     //         { "src": "507.jpg", "id": "507" },
     //         { "src": "498.png", "id": "498" },
     //         { "src": "473.png", "id": "473" },
     //         { "src": "467.png", "id": "467" },
     //         { "src": "463.png", "id": "463" },
     //         { "src": "477.png", "id": "477" },
     //         { "src": "488.png", "id": "488" },
     //         { "src": "503.png", "id": "503" },
     //         { "src": "502.png", "id": "502" },
     //         { "src": "489.png", "id": "489" },
     //         { "src": "476.png", "id": "476" },
     //         { "src": "462.png", "id": "462" },
     //         { "src": "474.png", "id": "474" },
     //         { "src": "460.png", "id": "460" },
     //         { "src": "448.png", "id": "448" },
     //         { "src": "514.jpg", "id": "514" },
     //         { "src": "500.png", "id": "500" },
     //         { "src": "501.png", "id": "501" },
     //         { "src": "515.jpg", "id": "515" },
     //         { "src": "449.png", "id": "449" },
     //         { "src": "461.png", "id": "461" },
     //         { "src": "475.png", "id": "475" },
     //         { "src": "478.png", "id": "478" },
     //         { "src": "450.png", "id": "450" },
     //         { "src": "444.png", "id": "444" },
     //         { "src": "493.png", "id": "493" },
     //         { "src": "487.png", "id": "487" },
     //         { "src": "486.png", "id": "486" },
     //         { "src": "492.png", "id": "492" },
     //         { "src": "445.png", "id": "445" },
     //         { "src": "451.png", "id": "451" },
     //         { "src": "479.png", "id": "479" },
     //         { "src": "447.png", "id": "447" },
     //         { "src": "453.png", "id": "453" },
     //         { "src": "484.png", "id": "484" },
     //         { "src": "490.png", "id": "490" },
     //         { "src": "491.png", "id": "491" },
     //         { "src": "485.png", "id": "485" },
     //         { "src": "452.png", "id": "452" },
     //         { "src": "446.png", "id": "446" },
     //         { "src": "442.png", "id": "442" },
     //         { "src": "456.png", "id": "456" },
     //         { "src": "481.png", "id": "481" },
     //         { "src": "495.png", "id": "495" },
     //         { "src": "494.png", "id": "494" },
     //         { "src": "480.png", "id": "480" },
     //         { "src": "457.png", "id": "457" },
     //         { "src": "443.png", "id": "443" },
     //         { "src": "455.png", "id": "455" },
     //         { "src": "441.png", "id": "441" },
     //         { "src": "469.png", "id": "469" },
     //         { "src": "496.png", "id": "496" },
     //         { "src": "482.png", "id": "482" },
     //         { "src": "509.png", "id": "509" },
     //         { "src": "508.png", "id": "508" },
     //         { "src": "483.png", "id": "483" },
     //         { "src": "497.png", "id": "497" },
     //         { "src": "468.png", "id": "468" },
     //         { "src": "440.png", "id": "440" },
     //         { "src": "454.png", "id": "454" },
     //         { "src": "435.png", "id": "435" },
     //         { "src": "434.png", "id": "434" },
     //         { "src": "436.png", "id": "436" },
     //         { "src": "437.png", "id": "437" },
     //     ]