questions = [{
        'text': 'The Life of Company X',
        'upper_text': 'This visualization shows a made up history timeline.',
        'id': 1,
        'dataset': './data/1.png',
        // 'answer': '917',
        // 'question_type': 1,
        // 'ques_index': 0,
        // 'type_index': 'a0',
    },
    {
        'text': 'The Population of City Y',
        'upper_text': 'This visualization shows a made up history timeline.',
        'id': 2,
        'dataset': './data/2.jpg',
        // 'answer': '929',
        // 'question_type': 1,
        // 'ques_index': 1,
        // 'type_index': 'a1',
        // 'nps': ['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff'],
    },
    {
        'text': 'One Day of Z',
        'upper_text': 'This visualization shows a made up history timeline.',
        'id': 3,
        'dataset': './data/3.jpeg',
        // 'answer': '929',
        // 'question_type': 1,
        // 'ques_index': 1,
        // 'type_index': 'a1',
        // 'nps': ['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff'],
    },
    {
        'text': 'One Day of Z',
        'upper_text': 'This visualization shows a made up history timeline.',
        'id': 4,
        'dataset': './data/4.jpg',
        // 'answer': '929',
        // 'question_type': 1,
        // 'ques_index': 1,
        // 'type_index': 'a1',
        // 'nps': ['aaa', 'bbb', 'ccc', 'ddd', 'eee', 'fff'],
    },


]

key = {
    '0': '1 day',
    '1': '2 days',
    '2': '2 days',
    '3': 'about 8.5 hours',
    '4': '3 days',
    '5': '1 event',
    '6': '1 day',
    '7': '4 days',
    '8': '4 days',
    '9': '8.5 hours',
    '10': '11 days',
    '11': '2 events'
}